// flow-typed signature: 035c0306cb9a65b96bd358d80052ed80
// flow-typed version: <<STUB>>/react-bootstrap_v^1.0.0-beta.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap/dist/react-bootstrap' {
  declare module.exports: any;
}

declare module 'react-bootstrap/dist/react-bootstrap.min' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/AbstractNav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/AbstractNavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Alert' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Badge' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Button' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Card' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CardColumns' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CardContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CardDeck' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CardGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CardImg' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Carousel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CarouselCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CarouselItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CloseButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Col' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Collapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Container' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Fade' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Feedback' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Figure' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FigureCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FigureImage' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Form' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormCheck' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormCheckInput' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormCheckLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormControl' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormText' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Image' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/InputGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Jumbotron' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ListGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ListGroupItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Media' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Modal' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalDialog' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalFooter' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalTitle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Nav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Navbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarBrand' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavDropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavLink' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Overlay' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/PageItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Pagination' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Popover' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Row' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/SafeAnchor' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/SelectableContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/SplitButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Tab' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabContainer' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabContent' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Table' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabPane' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Tabs' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ToggleButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Tooltip' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/BootstrapModalManager' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/createChainedFunction' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/createWithBsPrefix' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/divWithClassName' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/ElementChildren' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/triggerBrowserReflow' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/AbstractNav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/AbstractNavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Alert' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Badge' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Button' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Card' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CardColumns' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CardContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CardDeck' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CardGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CardImg' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Carousel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CarouselCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CarouselItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CloseButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Col' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Collapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Container' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/DropdownButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/DropdownItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Fade' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Feedback' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Figure' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FigureCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FigureImage' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Form' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormCheck' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormCheckInput' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormCheckLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormControl' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormText' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Image' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/InputGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Jumbotron' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ListGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ListGroupItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Media' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Modal' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalDialog' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalFooter' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalTitle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Nav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Navbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarBrand' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavDropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavLink' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Overlay' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/PageItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Pagination' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Popover' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Row' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/SafeAnchor' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/SelectableContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/SplitButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Tab' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/TabContainer' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/TabContent' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/TabContext' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Table' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/TabPane' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Tabs' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ToggleButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Tooltip' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/BootstrapModalManager' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/createChainedFunction' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/createWithBsPrefix' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/divWithClassName' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/ElementChildren' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/triggerBrowserReflow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap/dist/react-bootstrap.js' {
  declare module.exports: $Exports<'react-bootstrap/dist/react-bootstrap'>;
}
declare module 'react-bootstrap/dist/react-bootstrap.min.js' {
  declare module.exports: $Exports<'react-bootstrap/dist/react-bootstrap.min'>;
}
declare module 'react-bootstrap/es/AbstractNav.js' {
  declare module.exports: $Exports<'react-bootstrap/es/AbstractNav'>;
}
declare module 'react-bootstrap/es/AbstractNavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/AbstractNavItem'>;
}
declare module 'react-bootstrap/es/Alert.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Alert'>;
}
declare module 'react-bootstrap/es/Badge.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Badge'>;
}
declare module 'react-bootstrap/es/Breadcrumb.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Breadcrumb'>;
}
declare module 'react-bootstrap/es/BreadcrumbItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/BreadcrumbItem'>;
}
declare module 'react-bootstrap/es/Button.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Button'>;
}
declare module 'react-bootstrap/es/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ButtonGroup'>;
}
declare module 'react-bootstrap/es/ButtonToolbar.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ButtonToolbar'>;
}
declare module 'react-bootstrap/es/Card.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Card'>;
}
declare module 'react-bootstrap/es/CardColumns.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CardColumns'>;
}
declare module 'react-bootstrap/es/CardContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CardContext'>;
}
declare module 'react-bootstrap/es/CardDeck.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CardDeck'>;
}
declare module 'react-bootstrap/es/CardGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CardGroup'>;
}
declare module 'react-bootstrap/es/CardImg.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CardImg'>;
}
declare module 'react-bootstrap/es/Carousel.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Carousel'>;
}
declare module 'react-bootstrap/es/CarouselCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CarouselCaption'>;
}
declare module 'react-bootstrap/es/CarouselItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CarouselItem'>;
}
declare module 'react-bootstrap/es/CloseButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CloseButton'>;
}
declare module 'react-bootstrap/es/Col.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Col'>;
}
declare module 'react-bootstrap/es/Collapse.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Collapse'>;
}
declare module 'react-bootstrap/es/Container.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Container'>;
}
declare module 'react-bootstrap/es/Dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Dropdown'>;
}
declare module 'react-bootstrap/es/DropdownButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownButton'>;
}
declare module 'react-bootstrap/es/DropdownItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownItem'>;
}
declare module 'react-bootstrap/es/DropdownMenu.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownMenu'>;
}
declare module 'react-bootstrap/es/DropdownToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownToggle'>;
}
declare module 'react-bootstrap/es/Fade.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Fade'>;
}
declare module 'react-bootstrap/es/Feedback.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Feedback'>;
}
declare module 'react-bootstrap/es/Figure.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Figure'>;
}
declare module 'react-bootstrap/es/FigureCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FigureCaption'>;
}
declare module 'react-bootstrap/es/FigureImage.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FigureImage'>;
}
declare module 'react-bootstrap/es/Form.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Form'>;
}
declare module 'react-bootstrap/es/FormCheck.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormCheck'>;
}
declare module 'react-bootstrap/es/FormCheckInput.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormCheckInput'>;
}
declare module 'react-bootstrap/es/FormCheckLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormCheckLabel'>;
}
declare module 'react-bootstrap/es/FormContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormContext'>;
}
declare module 'react-bootstrap/es/FormControl.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormControl'>;
}
declare module 'react-bootstrap/es/FormGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormGroup'>;
}
declare module 'react-bootstrap/es/FormLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormLabel'>;
}
declare module 'react-bootstrap/es/FormText.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormText'>;
}
declare module 'react-bootstrap/es/Image.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Image'>;
}
declare module 'react-bootstrap/es/index.js' {
  declare module.exports: $Exports<'react-bootstrap/es/index'>;
}
declare module 'react-bootstrap/es/InputGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/InputGroup'>;
}
declare module 'react-bootstrap/es/Jumbotron.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Jumbotron'>;
}
declare module 'react-bootstrap/es/ListGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ListGroup'>;
}
declare module 'react-bootstrap/es/ListGroupItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ListGroupItem'>;
}
declare module 'react-bootstrap/es/Media.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Media'>;
}
declare module 'react-bootstrap/es/Modal.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Modal'>;
}
declare module 'react-bootstrap/es/ModalBody.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalBody'>;
}
declare module 'react-bootstrap/es/ModalContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalContext'>;
}
declare module 'react-bootstrap/es/ModalDialog.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalDialog'>;
}
declare module 'react-bootstrap/es/ModalFooter.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalFooter'>;
}
declare module 'react-bootstrap/es/ModalHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalHeader'>;
}
declare module 'react-bootstrap/es/ModalTitle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalTitle'>;
}
declare module 'react-bootstrap/es/Nav.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Nav'>;
}
declare module 'react-bootstrap/es/Navbar.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Navbar'>;
}
declare module 'react-bootstrap/es/NavbarBrand.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarBrand'>;
}
declare module 'react-bootstrap/es/NavbarCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarCollapse'>;
}
declare module 'react-bootstrap/es/NavbarContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarContext'>;
}
declare module 'react-bootstrap/es/NavbarToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarToggle'>;
}
declare module 'react-bootstrap/es/NavContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavContext'>;
}
declare module 'react-bootstrap/es/NavDropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavDropdown'>;
}
declare module 'react-bootstrap/es/NavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavItem'>;
}
declare module 'react-bootstrap/es/NavLink.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavLink'>;
}
declare module 'react-bootstrap/es/Overlay.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Overlay'>;
}
declare module 'react-bootstrap/es/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-bootstrap/es/OverlayTrigger'>;
}
declare module 'react-bootstrap/es/PageItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/PageItem'>;
}
declare module 'react-bootstrap/es/Pagination.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Pagination'>;
}
declare module 'react-bootstrap/es/Popover.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Popover'>;
}
declare module 'react-bootstrap/es/ProgressBar.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ProgressBar'>;
}
declare module 'react-bootstrap/es/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ResponsiveEmbed'>;
}
declare module 'react-bootstrap/es/Row.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Row'>;
}
declare module 'react-bootstrap/es/SafeAnchor.js' {
  declare module.exports: $Exports<'react-bootstrap/es/SafeAnchor'>;
}
declare module 'react-bootstrap/es/SelectableContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/SelectableContext'>;
}
declare module 'react-bootstrap/es/SplitButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/SplitButton'>;
}
declare module 'react-bootstrap/es/Tab.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Tab'>;
}
declare module 'react-bootstrap/es/TabContainer.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabContainer'>;
}
declare module 'react-bootstrap/es/TabContent.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabContent'>;
}
declare module 'react-bootstrap/es/TabContext.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabContext'>;
}
declare module 'react-bootstrap/es/Table.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Table'>;
}
declare module 'react-bootstrap/es/TabPane.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabPane'>;
}
declare module 'react-bootstrap/es/Tabs.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Tabs'>;
}
declare module 'react-bootstrap/es/ThemeProvider.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ThemeProvider'>;
}
declare module 'react-bootstrap/es/ToggleButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ToggleButton'>;
}
declare module 'react-bootstrap/es/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ToggleButtonGroup'>;
}
declare module 'react-bootstrap/es/Tooltip.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Tooltip'>;
}
declare module 'react-bootstrap/es/utils/BootstrapModalManager.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/BootstrapModalManager'>;
}
declare module 'react-bootstrap/es/utils/createChainedFunction.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/createChainedFunction'>;
}
declare module 'react-bootstrap/es/utils/createWithBsPrefix.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/createWithBsPrefix'>;
}
declare module 'react-bootstrap/es/utils/divWithClassName.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/divWithClassName'>;
}
declare module 'react-bootstrap/es/utils/ElementChildren.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/ElementChildren'>;
}
declare module 'react-bootstrap/es/utils/triggerBrowserReflow.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/triggerBrowserReflow'>;
}
declare module 'react-bootstrap/lib/AbstractNav.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/AbstractNav'>;
}
declare module 'react-bootstrap/lib/AbstractNavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/AbstractNavItem'>;
}
declare module 'react-bootstrap/lib/Alert.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Alert'>;
}
declare module 'react-bootstrap/lib/Badge.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Badge'>;
}
declare module 'react-bootstrap/lib/Breadcrumb.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Breadcrumb'>;
}
declare module 'react-bootstrap/lib/BreadcrumbItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/BreadcrumbItem'>;
}
declare module 'react-bootstrap/lib/Button.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Button'>;
}
declare module 'react-bootstrap/lib/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ButtonGroup'>;
}
declare module 'react-bootstrap/lib/ButtonToolbar.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ButtonToolbar'>;
}
declare module 'react-bootstrap/lib/Card.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Card'>;
}
declare module 'react-bootstrap/lib/CardColumns.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CardColumns'>;
}
declare module 'react-bootstrap/lib/CardContext.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CardContext'>;
}
declare module 'react-bootstrap/lib/CardDeck.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CardDeck'>;
}
declare module 'react-bootstrap/lib/CardGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CardGroup'>;
}
declare module 'react-bootstrap/lib/CardImg.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CardImg'>;
}
declare module 'react-bootstrap/lib/Carousel.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Carousel'>;
}
declare module 'react-bootstrap/lib/CarouselCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CarouselCaption'>;
}
declare module 'react-bootstrap/lib/CarouselItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CarouselItem'>;
}
declare module 'react-bootstrap/lib/CloseButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CloseButton'>;
}
declare module 'react-bootstrap/lib/Col.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Col'>;
}
declare module 'react-bootstrap/lib/Collapse.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Collapse'>;
}
declare module 'react-bootstrap/lib/Container.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Container'>;
}
declare module 'react-bootstrap/lib/Dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Dropdown'>;
}
declare module 'react-bootstrap/lib/DropdownButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/DropdownButton'>;
}
declare module 'react-bootstrap/lib/DropdownItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/DropdownItem'>;
}
declare module 'react-bootstrap/lib/DropdownMenu.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/DropdownMenu'>;
}
declare module 'react-bootstrap/lib/DropdownToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/DropdownToggle'>;
}
declare module 'react-bootstrap/lib/Fade.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Fade'>;
}
declare module 'react-bootstrap/lib/Feedback.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Feedback'>;
}
declare module 'react-bootstrap/lib/Figure.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Figure'>;
}
declare module 'react-bootstrap/lib/FigureCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FigureCaption'>;
}
declare module 'react-bootstrap/lib/FigureImage.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FigureImage'>;
}
declare module 'react-bootstrap/lib/Form.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Form'>;
}
declare module 'react-bootstrap/lib/FormCheck.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormCheck'>;
}
declare module 'react-bootstrap/lib/FormCheckInput.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormCheckInput'>;
}
declare module 'react-bootstrap/lib/FormCheckLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormCheckLabel'>;
}
declare module 'react-bootstrap/lib/FormContext.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormContext'>;
}
declare module 'react-bootstrap/lib/FormControl.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormControl'>;
}
declare module 'react-bootstrap/lib/FormGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormGroup'>;
}
declare module 'react-bootstrap/lib/FormLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormLabel'>;
}
declare module 'react-bootstrap/lib/FormText.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormText'>;
}
declare module 'react-bootstrap/lib/Image.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Image'>;
}
declare module 'react-bootstrap/lib/index.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/index'>;
}
declare module 'react-bootstrap/lib/InputGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/InputGroup'>;
}
declare module 'react-bootstrap/lib/Jumbotron.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Jumbotron'>;
}
declare module 'react-bootstrap/lib/ListGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ListGroup'>;
}
declare module 'react-bootstrap/lib/ListGroupItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ListGroupItem'>;
}
declare module 'react-bootstrap/lib/Media.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Media'>;
}
declare module 'react-bootstrap/lib/Modal.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Modal'>;
}
declare module 'react-bootstrap/lib/ModalBody.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalBody'>;
}
declare module 'react-bootstrap/lib/ModalContext.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalContext'>;
}
declare module 'react-bootstrap/lib/ModalDialog.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalDialog'>;
}
declare module 'react-bootstrap/lib/ModalFooter.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalFooter'>;
}
declare module 'react-bootstrap/lib/ModalHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalHeader'>;
}
declare module 'react-bootstrap/lib/ModalTitle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalTitle'>;
}
declare module 'react-bootstrap/lib/Nav.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Nav'>;
}
declare module 'react-bootstrap/lib/Navbar.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Navbar'>;
}
declare module 'react-bootstrap/lib/NavbarBrand.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarBrand'>;
}
declare module 'react-bootstrap/lib/NavbarCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarCollapse'>;
}
declare module 'react-bootstrap/lib/NavbarContext.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarContext'>;
}
declare module 'react-bootstrap/lib/NavbarToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarToggle'>;
}
declare module 'react-bootstrap/lib/NavContext.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavContext'>;
}
declare module 'react-bootstrap/lib/NavDropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavDropdown'>;
}
declare module 'react-bootstrap/lib/NavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavItem'>;
}
declare module 'react-bootstrap/lib/NavLink.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavLink'>;
}
declare module 'react-bootstrap/lib/Overlay.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Overlay'>;
}
declare module 'react-bootstrap/lib/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/OverlayTrigger'>;
}
declare module 'react-bootstrap/lib/PageItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/PageItem'>;
}
declare module 'react-bootstrap/lib/Pagination.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Pagination'>;
}
declare module 'react-bootstrap/lib/Popover.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Popover'>;
}
declare module 'react-bootstrap/lib/ProgressBar.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ProgressBar'>;
}
declare module 'react-bootstrap/lib/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ResponsiveEmbed'>;
}
declare module 'react-bootstrap/lib/Row.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Row'>;
}
declare module 'react-bootstrap/lib/SafeAnchor.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/SafeAnchor'>;
}
declare module 'react-bootstrap/lib/SelectableContext.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/SelectableContext'>;
}
declare module 'react-bootstrap/lib/SplitButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/SplitButton'>;
}
declare module 'react-bootstrap/lib/Tab.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Tab'>;
}
declare module 'react-bootstrap/lib/TabContainer.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/TabContainer'>;
}
declare module 'react-bootstrap/lib/TabContent.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/TabContent'>;
}
declare module 'react-bootstrap/lib/TabContext.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/TabContext'>;
}
declare module 'react-bootstrap/lib/Table.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Table'>;
}
declare module 'react-bootstrap/lib/TabPane.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/TabPane'>;
}
declare module 'react-bootstrap/lib/Tabs.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Tabs'>;
}
declare module 'react-bootstrap/lib/ThemeProvider.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ThemeProvider'>;
}
declare module 'react-bootstrap/lib/ToggleButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ToggleButton'>;
}
declare module 'react-bootstrap/lib/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ToggleButtonGroup'>;
}
declare module 'react-bootstrap/lib/Tooltip.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Tooltip'>;
}
declare module 'react-bootstrap/lib/utils/BootstrapModalManager.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/BootstrapModalManager'>;
}
declare module 'react-bootstrap/lib/utils/createChainedFunction.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/createChainedFunction'>;
}
declare module 'react-bootstrap/lib/utils/createWithBsPrefix.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/createWithBsPrefix'>;
}
declare module 'react-bootstrap/lib/utils/divWithClassName.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/divWithClassName'>;
}
declare module 'react-bootstrap/lib/utils/ElementChildren.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/ElementChildren'>;
}
declare module 'react-bootstrap/lib/utils/triggerBrowserReflow.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/triggerBrowserReflow'>;
}
