backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under public/uploads
# public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/md"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
