backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under public/uploads
# public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/md"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "authors"
    label: "Författare"
    label_singular: "Författare"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Namn", name: "title", widget: "string"}
      - {label: "Porträtt", name: "thumbnail", widget: "image"}
      - {label: "Beskrivning", name: "body", widget: "markdown"}
  - name: "books"
    label: "Böcker"
    label_singular: "Bok"
    folder: "content/books"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Författre", name: "author", widget: "string"}
      - {label: "Illustrationer", name: "illustrations", widget: "string", required: false}
      - {label: "ISBN", name: "isbn", widget: "string", pattern: ["[0-9]*[-| ][0-9]*[-| ][0-9]*[-| ][0-9]*[-| ][0-9]*", "Must be ISBN format"]}
      - {label: "Publicerad", name: "published", widget: "boolean", required: false}
      - {label: "Utgått", name: "discontinued", widget: "boolean", required: false}
      - {label: "Omslag", name: "thumbnail", widget: "image"}
      - {label: "Pris", name: "price", widget: "number", valueType: 'int', min: 1, max: 1000}
      - {label: "Kort Beskrivning", name: "shortDescription", widget: "text"}
      - {label: "Detaljerad Beskrivning", name: "longDescription", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Utgivningsmånad", name: "publishMonth", widget: "date", format: 'MMM -YY'}
      - {label: "Bindning", name: "binding", widget: "select", options: ['Kartonnage', 'Häftad', 'Inbunden', 'Flexband', 'Danskt band', 'CD-bok']}
      - {label: "Rekommenderad ålder", name: "age", widget: "number", valueType: 'int', min: 1, max: 99}
      - {label: "Antal sidor", name: "numPages", widget: "number", valueType: 'int', min: 1, max: 1000}
      - label: 'Översatt bok'
        name: 'translated'
        widget: 'object'
        fields:
        - {label: "Översättning", name: "translator", widget: "string"}
        - {label: "Orginaltitel", name: "originalTitle", widget: "string"}
      - label: 'Ljudbok'
        name: 'audio'
        widget: 'object'
        fields:
        - {label: "Speltid", name: "duration", widget: "string"}
        - {label: "Uppläsare", name: "reciter", widget: "string"}
